/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceMenu: typeof import('./src/components/AppearanceMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemNotificationBanner: typeof import('./src/components/SystemNotificationBanner.vue')['default']
    UAlert: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    ULink: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.1_f49454208c45f56c1ab6dbcdf13e446f/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
