packages:
  - apps/*
  - packages/*
allowBuilds:
  bcrypt: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@eleansphere/*'
  - '@types/node@22.20.3'
  - '@vitest/mocker@5.0.1'
  - '@vitest/spy@5.0.1'
  - vitest@5.0.1
